Year End Reports
bcgov/EDUC-GRAD-DISTRIBUTION-API pull request #191
Opened 2023-06-12 16:51 UTC by arybakov-cgi

2023-07-17 15:41 UTC, cditcher requested changes

2023-07-17 16:49 UTC, arybakov-cgi commented on api/src/main/java/ca/bc/gov/educ/api/distribution/service/SchoolService.java
>  			exception.setExceptionName("SCHOOL-API IS DOWN");
That exception message object is referenced in the parent calls and idea is to display it on UI and batch history. That design is used in all processes. May impact UI or batch history functionality. Could be a major redesign efforts.

2023-07-18 16:27 UTC, cditcher approved these changes

2023-07-19 16:34 UTC, cditcher approved these changes

2023-07-21 17:15 UTC, cditcher approved these changes

2023-07-21 20:21 UTC, merged